---
build:
  distFolder: public
  installCmd: npm ci
  buildCmd: npm run build
  artifacts:
    - node_modules
    - public

run:
  CMD: node server.js
  workDir: /home/app
  port: 3000

env:
  - NODE_ENV=production
