---
meta:
  version: 20

build:
  installCmd: apt-get update && apt-get install -y chromium-browser && npm ci
  skip: false

run:
  CMD: npm run start
  scriptName: server.js
  containerPort: 3000
  nodeArguments: --experimental-global-webcrypto

env:
  - NODE_ENV=production
  - NODE_OPTIONS=--experimental-global-webcrypto
  - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
  - PUPPETEER_CACHE_DIR=/tmp/puppeteer
  - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
