---
meta:
  version: 20

build:
  installCmd: npm install --omit=dev --legacy-peer-deps
  skip: false

run:
  CMD: npm start
  scriptName: server.js
  containerPort: 3000
  nodeArguments: --experimental-global-webcrypto

env:
  - NODE_ENV=production
  - NODE_OPTIONS=--experimental-global-webcrypto
  - NPM_CONFIG_LEGACY_PEER_DEPS=true
