# .amvera.yml
services:
  web:
    environment: docker
    tool: docker

    build:
      dockerfile: Dockerfile   # если у вас Dockerfile в корне репо

    run:
      containerPort: 3000
      env:
        PORT: "3000"
