---
meta:
  version: 20

build:
  installCmd: npm ci
  skip: false

run:
  CMD: npm run start
  scriptName: server.js
  containerPort: 3000
  nodeArguments: --experimental-global-webcrypto
  healthCheckPath: /api/health
  healthCheckInitialDelay: 10
  healthCheckInterval: 10

env:
  - NODE_ENV=production
  - NODE_OPTIONS=--experimental-global-webcrypto
