---
meta:
  version: 20

build:
  installCmd: npm ci
  buildCmd: npx puppeteer browsers install chrome
  skip: false

run:
  CMD: npm run start
  scriptName: server.js
  containerPort: 3000
  nodeArguments: --experimental-global-webcrypto

env:
  - NODE_ENV=production
  - NODE_OPTIONS=--experimental-global-webcrypto
  - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false
  - PUPPETEER_EXECUTABLE_PATH=/root/.cache/puppeteer/chrome/linux-141.0.7390.122/chrome-linux64/chrome
